version: '3.3'

services:
   goodreads:
     image: scrap_udemy_courses
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - ./output:/output/:rw
     depends_on:
       - splash
   splash:
     image: scrapinghub/splash
