version: '3.3'

services:
   udemy:
     image: scrap_udemy_courses
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       - SPLASH_URL=http://splash:8050
       - search_keyword=flask+python
     volumes:
       - ./output:/output/:rw
     depends_on:
       - splash
   splash:
     image: scrapinghub/splash
